### PR TITLE
Add test to verify lifetime extension

### PR DESCRIPTION
**Pull request by nonsensery**
#### Summary

This PR adds a test to verify the behavior of `LockedState.withLockExtendingLifetimeOfState(_:)`.

#### Discussion

The desired behavior is that the old state object not be deallocated until after the lock is released.

During the review of #107, we did not come up with a way to test the expected behavior of this method. An idea for testing it popped into my head, so I tried it out.

This test attempts to acquire the lock when the state object is deallocated. If the lock is still held at that point, the test fails. (Unfortunately, it fails by crashing, but I don't know a way around that.)

#### Verification

I ran this test with the implementations of `withLockExtendingLifetimeOfState` from both #97 (test failed) and #107 (test passed).

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by nonsensery** [comment]
Oops, I missed a line when committing my changes. It should compile now 😅

**Review by glessard — APPROVED** [review]
Great idea. Thanks!

**Pull request merged**
