### PR TITLE
Refactoring some import conditions

### PR DESCRIPTION
**Pull request by iCharlesHu**

### CODE REVIEW

**Comment by iCharlesHu** [comment]
@swift-ci please test

**Review by Catfish-Man — APPROVED** [review]
thank you!

**Comment by jmschonfeld** [comment]
Looks like there are some build failures here about usages of NSLocale in places not guarded by FOUNDATION_FRAMEWORK

**Comment by iCharlesHu** [comment]
@swift-ci please test

**Comment by iCharlesHu** [comment]
Fixed the build and test failure (hopefully)

**Comment by iCharlesHu** [comment]
Linux failure is fixed in https://github.com/apple/swift-syntax/pull/2312
Hopefully we'll get a new snapshot soon

**Pull request merged**
