### PR TITLE
Predicate Regex Support

### PR DESCRIPTION
**Pull request by jmschonfeld**
This adds support for using regular expressions from within a `Predicate`

### CODE REVIEW

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Review by itingliu — APPROVED** [review]

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Pull request merged**
