### PR TITLE
`Predicate` Variadic Generics Adoption

### PR DESCRIPTION
**Pull request by jmschonfeld**
This adopts the variadic generics feature for all predicate APIs to support multiple inputs for predicates

### CODE REVIEW

**Review by itingliu — APPROVED** [review]
Following the [variadic generics proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md) this looks good to me

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by iCharlesHu** [comment]
@jmschonfeld is the compiler crashing expected?

**Comment by jmschonfeld** [comment]
> @jmschonfeld is the compiler crashing expected?

Sadly not expected, but @slavapestov is working on getting a fix into the compiler to correct this crash. I'll hold off on merging this until we have a snapshot available with the fix

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
Moving this back to draft state as I tackle a few outstanding issues here

**Comment by jmschonfeld** [comment]
Closing, will revisit with a new PR rebased on `main`

**Pull request closed without merging**
