### PR TITLE
WIP: IANA Character Set Names.

### PR DESCRIPTION
**Pull request by YOCKOW**
This is a draft PR for an upcoming Foundation Evolution proposal.

Context: https://forums.swift.org/t/swift-foundation-now-available/73530/26

### CODE REVIEW

**Comment by YOCKOW** [comment]
@swift-ci Please test

**Comment by itingliu** [comment]
Did you mean to propose these additions as an API? If so, the first step would be posting a pitch on the forum according to the [evolution process](https://github.com/apple/swift-foundation/blob/79dc3091aa7ed7ff4240f3a4dfc768b76b5423bd/Evolution.md?plain=1#L10)

**Comment by itingliu** [comment]
This is the pitch right? https://forums.swift.org/t/pitch-foundation-iana-character-set-names/74623

**Comment by YOCKOW** [comment]
> This is the pitch right? https://forums.swift.org/t/pitch-foundation-iana-character-set-names/74623

Yes, that' it.
I'm sorry for forgetting to add the link.

**Pull request closed without merging**
