### PR TITLE
Move files shared by FoundationEssentials and FoundationInternationalization to _FoundationInternals

### PR DESCRIPTION
**Pull request by itingliu**
- Add a folder `Sources/_FoundationInternals` to host internal files needed by both modules. Move LockedState.swift there.
- Add `Sources/_FoundationInternals` as a symlink inside both modules, so the files under `Sources/_FoundationInternals` appear as their own sources respectively.

### CODE REVIEW

**Comment by itingliu** [comment]
@swift-ci please test

**Review by jmschonfeld — APPROVED** [review]

**Review by iCharlesHu — APPROVED** [review]
🤩🤩

**Review by glessard — APPROVED** [review]
!!

**Comment by compnerd** [comment]
This would be greatly appreciated by me - I've been waiting for this change to start uploading changes for the work to enable Windows.

**Comment by itingliu** [comment]
@swift-ci please test

**Pull request merged**
