### PR TITLE
Implementation for "The `DiscreteFormatStyle` Protocol" proposal

### PR DESCRIPTION
**Pull request by theMomax**
This PR lists all changes proposed in the ["The `DiscreteFormatStyle` Protocol](https://github.com/apple/swift-foundation/pull/340), with few exceptions:

1. Conformance for `Date.ComponentsFormatStyle` is not included as the type is not part of FoundationPreview yet
2. Conformance for `Date.ISO8601FormatStyle` is not included to the type's recent rewrite.

### CODE REVIEW

**Comment by theMomax** [comment]
@swift-ci please test

**Comment by theMomax** [comment]
@swift-ci please test

**Comment by theMomax** [comment]
@swift-ci please test

**Comment by theMomax** [comment]
@swift-ci please test

**Comment by theMomax** [comment]
@swift-ci please test

**Review by itingliu — APPROVED** [review]

**Pull request merged**
