### PR TITLE
DNM: testing

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
From a local `--parallel` run:

```
Test Suite 'Selected tests' started at 2024-05-09 11:15:11.445
Test Suite 'DateTests' started at 2024-05-09 11:15:11.446
Test Case 'DateTests.testDescriptionDistantFuture' started at 2024-05-09 11:15:11.446
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DateTests.swift:102: error: DateTests.testDescriptionDistantFuture : XCTAssertEqual failed: ("4001-01-01 00:00:00 +0000") is not equal to ("<description unavailable>") -
Test Case 'DateTests.testDescriptionDistantFuture' failed (0.001 seconds)
Test Suite 'DateTests' failed at 2024-05-09 11:15:11.447
         Executed 1 test, with 1 failure (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'Selected tests' failed at 2024-05-09 11:15:11.447
         Executed 1 test, with 1 failure (0 unexpected) in 0.001 (0.001) seconds

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.455
Test Suite 'DateTests' started at 2024-05-09 11:15:11.455
Test Case 'DateTests.testDescriptionDistantPast' started at 2024-05-09 11:15:11.455
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DateTests.swift:97: error: DateTests.testDescriptionDistantPast : XCTAssertEqual failed: ("0000-12-30 00:00:00 +0000") is not equal to ("<description unavailable>") -
Test Case 'DateTests.testDescriptionDistantPast' failed (0.011 seconds)
Test Suite 'DateTests' failed at 2024-05-09 11:15:11.466
         Executed 1 test, with 1 failure (0 unexpected) in 0.011 (0.011) seconds
Test Suite 'Selected tests' failed at 2024-05-09 11:15:11.467
         Executed 1 test, with 1 failure (0 unexpected) in 0.011 (0.011) seconds

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.603
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.604
Test Case 'FileManagerTests.testContentsAtPath' started at 2024-05-09 11:15:11.604
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.601
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.603
Test Case 'FileManagerTests.testContentsEqualAtPaths' started at 2024-05-09 11:15:11.603
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.934
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.testStringDeletingLastPathComponent' started at 2024-05-09 11:15:09.934
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:235: error: DataIOTests.testStringDeletingLastPathComponent : XCTAssertEqual failed: ("") is not equal to ("/a/b") -
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:237: error: DataIOTests.testStringDeletingLastPathComponent : XCTAssertEqual failed: ("") is not equal to ("/") -
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:239: error: DataIOTests.testStringDeletingLastPathComponent : XCTAssertEqual failed: ("S:\") is not equal to ("/") -
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:240: error: DataIOTests.testStringDeletingLastPathComponent : XCTAssertEqual failed: ("") is not equal to ("/a/b") -
Test Case 'DataIOTests.testStringDeletingLastPathComponent' failed (0.0 seconds)
Test Suite 'DataIOTests' failed at 2024-05-09 11:15:09.934
         Executed 1 test, with 4 failures (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'Selected tests' failed at 2024-05-09 11:15:09.934
         Executed 1 test, with 4 failures (0 unexpected) in 0.0 (0.0) seconds

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.929
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.931
Test Case 'DataIOTests.test_largeFile' started at 2024-05-09 11:15:09.931
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.931
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_basicReadWrite' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.931
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_writeFailure' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.934
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_readWriteAtomic' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.934
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_slicedReadWrite' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.934
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_emptyFile' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.925
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.928
Test Case 'DataIOTests.test_writeToSpecialFile' started at 2024-05-09 11:15:09.928
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:229: error: DataIOTests.test_writeToSpecialFile : XCTAssertNoThrow failed: threw error "CocoaError(code: FoundationEssentials.CocoaError.Code(rawValue: 518), userInfo: [:])" -
Test Case 'DataIOTests.test_writeToSpecialFile' failed (0.001 seconds)
Test Suite 'DataIOTests' failed at 2024-05-09 11:15:09.929
         Executed 1 test, with 1 failure (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'Selected tests' failed at 2024-05-09 11:15:09.931
         Executed 1 test, with 1 failure (0 unexpected) in 0.001 (0.001) seconds

Test Suite 'Selected tests' started at 2024-05-09 11:15:09.931
Test Suite 'DataIOTests' started at 2024-05-09 11:15:09.934
Test Case 'DataIOTests.test_readWriteMapped' started at 2024-05-09 11:15:09.934
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.780
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.781
Test Case 'FileManagerTests.testCopyFileAtPathToPath' started at 2024-05-09 11:15:11.781
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.780
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.781
Test Case 'FileManagerTests.testCopyItemAtPathToPath' started at 2024-05-09 11:15:11.781
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.780
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.781
Test Case 'FileManagerTests.testCreateDirectoryAtPath' started at 2024-05-09 11:15:11.781
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testImplicitlyConvertibleFileAttributes' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testCreateSymbolicLinkAtPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.845
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.847
Test Case 'FileManagerTests.testCurrentWorkingDirectory' started at 2024-05-09 11:15:11.847
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.845
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.847
Test Case 'FileManagerTests.testRemoveItemAtPath' started at 2024-05-09 11:15:11.847
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.845
Test Case 'FileManagerTests.testResolveSymlinksViaGetAttrList' started at 2024-05-09 11:15:11.845
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testMoveItemAtPathToPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testFileExistsAtPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testMalformedModificationDateAttribute' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testSubpathsOfDirectoryAtPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.845
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.847
Test Case 'FileManagerTests.testDirectoryContentsAtPath' started at 2024-05-09 11:15:11.847
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testFileSystemAttributesAtPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:11.832
Test Suite 'FileManagerTests' started at 2024-05-09 11:15:11.832
Test Case 'FileManagerTests.testLinkFileAtPathToPath' started at 2024-05-09 11:15:11.832
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:14.576
Test Suite 'JSONEncoderTests' started at 2024-05-09 11:15:14.576
Test Case 'JSONEncoderTests.test_json5PassJSONFiles' started at 2024-05-09 11:15:14.576
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:14.589
Test Suite 'JSONEncoderTests' started at 2024-05-09 11:15:14.590
Test Case 'JSONEncoderTests.test_json5Spec' started at 2024-05-09 11:15:14.590
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:14.566
Test Suite 'JSONEncoderTests' started at 2024-05-09 11:15:14.568
Test Case 'JSONEncoderTests.test_JSONFailTests' started at 2024-05-09 11:15:14.568
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:14.557
Test Suite 'JSONEncoderTests' started at 2024-05-09 11:15:14.559
Test Case 'JSONEncoderTests.test_JSONPassTests' started at 2024-05-09 11:15:14.559
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:16.919
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:16.921
Test Case 'TestPropertyListEncoder.test_5616259' started at 2024-05-09 11:15:16.921
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:16.918
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:16.919
Test Case 'TestPropertyListEncoder.test_5877417' started at 2024-05-09 11:15:16.919
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:16.969
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:16.969
Test Case 'TestPropertyListEncoder.test_genericProperties_XML' started at 2024-05-09 11:15:16.969
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:18.548
Test Suite 'URLTests' started at 2024-05-09 11:15:18.548
Test Case 'URLTests.testAppendFamilyDirectoryHint' started at 2024-05-09 11:15:18.548
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:19.066
Test Suite 'URLTests' started at 2024-05-09 11:15:19.072
Test Case 'URLTests.testURLFilePathInitializer' started at 2024-05-09 11:15:19.072
S:\SourceCache\swift-project\swift-foundation\Tests\FoundationEssentialsTests\URLTests.swift:307: error: URLTests.testURLFilePathInitializer : XCTAssertTrue failed -
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:18.475
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:18.477
Test Case 'TestPropertyListEncoder.test_genericProperties_binary' started at 2024-05-09 11:15:18.477
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:18.504
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:18.509
Test Case 'TestPropertyListEncoder.test_xmlErrors' started at 2024-05-09 11:15:18.509
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:18.491
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:18.493
Test Case 'TestPropertyListEncoder.test_plistWithBadUTF8' started at 2024-05-09 11:15:18.493
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132

Test Suite 'Selected tests' started at 2024-05-09 11:15:18.491
Test Suite 'TestPropertyListEncoder' started at 2024-05-09 11:15:18.491
Test Case 'TestPropertyListEncoder.test_invalidNSDataKey_82142612' started at 2024-05-09 11:15:18.491
FoundationEssentials/URL.swift:2103: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    (null)                             0x00007ff99e0a5870 swift_stdlib_reportFatalErrorInFile + 132
```

CC: @parkera @jmschonfeld @jrflat - the URL.swift:2103 fatal error is the interesting bit - it is ultimately caused by the file path representation on Windows.

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci  please test windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@jmschonfeld @parkera - I don't understand this failure unfortunately. Locally I am not seeing this precondition failure. Instead, locally, I am seeing 10 failures:
- 2 in Date
- 8 in FileManager

It would be nice to get that replicated on the CI here so that we can work towards enabling the test suite as a pre-commit requirement.

**Comment by jmschonfeld** [comment]
> @jmschonfeld @parkera - I don't understand this failure unfortunately. Locally I am not seeing this precondition failure. 

It looks like the precondition failure is happening because `SHGetFolderPath` is returning `0x80070003`. It looks like we might be running into this scenario that someone described here: https://devblogs.microsoft.com/oldnewthing/20200520-00/?p=103775. To alleviate the problem, we can make `_url(for:)` return `nil` instead of a precondition failure when `SHGetFolderPath` fails, which will bubble up to the caller with no found search paths. I expect that might cause the unit test to fail instead of crash and we can adjust from there. But I think the secondary issue is investigating whether it's "correct" that the CI user cannot appropriately find the Documents folder. If so, maybe we remove that directory from the windows test due to this behavior or conditionalize it for CI.

**Comment by compnerd** [comment]
This would also explain why I was unable to reproduce this failure locally - I don't mess with my environment 😂

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Remaining failure:

```
Test Case 'DataIOTests.test_writeToSpecialFile' started at 2024-06-12 21:50:12.232

C:\source\swift-foundation\Tests\FoundationEssentialsTests\DataIOTests.swift:236: error: DataIOTests.test_writeToSpecialFile : XCTAssertNoThrow failed: threw error "CocoaError(code: FoundationEssentials.CocoaError.Code(rawValue: 512), userInfo: ["NSFilePath": AnyHashable("/C:/source/swift-foundation/CON"), "NSURL": AnyHashable(CON -- file:///C:/source/swift-foundation/), "NSUnderlyingError": AnyHashable(FoundationEssentials.POSIXError(code: CRT.POSIXErrorCode.EBADF))])" - 

Test Case 'DataIOTests.test_writeToSpecialFile' failed (0.002 seconds)
```

Interesting that this only seems to trigger on the CI host, not locally.

**Comment by parkera** [comment]
We can close this one now, right?

**Comment by compnerd** [comment]
Yes, I think that we can close this off now, with Windows testing being included.

**Pull request closed without merging**
