### PR TITLE
Use `__owned` parameter modifier

### PR DESCRIPTION
**Pull request by glessard**
Using the `consuming` parameter modifier for copyable (aka normal) types is deferred from swift 5.9. This uses the older `__owned` modifier instead, and consumes the parameter into a `var` as the first statement. This should generate the same code. This fixes a compilation error in `swift-foundation`'s Linux CI.

### CODE REVIEW

**Comment by glessard** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
Based on CI, looks like `JSON5Scanner.swift` needs to be updated too

**Review by jmschonfeld — APPROVED** [review]
Looks like linux CI passes now, thanks!

**Review by iCharlesHu — APPROVED** [review]
It looks like Linux is passing now!

**Pull request merged**
