### PR TITLE
Variadic Generics Support for Predicate

### PR DESCRIPTION
**Pull request by jmschonfeld**
Adds variadic input support for Predicate and its associated types and APIs

Resolves rdar://103142402

### CODE REVIEW

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Review by itingliu — APPROVED** [review]

**Pull request merged**
