### PR TITLE
6.0: Fix WASI support 

### PR DESCRIPTION
**Pull request by MaxDesiatov**
**Explanation**: these patches restore support for WASI that was available in `swift-corelibs-foundation` before it was recored.
**Scope**: Isolated to WASI codepaths.
**Risk**: Low due to isolated scope.
**Testing**: Tested manually for WASI, on CI with the existing test suite for other platforms.
**Issue**: rdar://133231577
**Reviewer**: @MaxDesiatov and @jmschonfeld

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@kateinoigakukun is there anything else you'd like to cherry-pick here if possible, keeping changes at low risk?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@kateinoigakukun have you seen this failure on Linux before, or is this branch missing some commits from `main` that would fix this?

```
FoundationEssentialsTests/JSONEncoderTests.swift:2402: Fatal error: Unexpectedly found nil while unwrapping an Optional value

*** Signal 4: Backtracing from 0x7fd04cf28314... done ***

*** Program crashed: Illegal instruction at 0x00007fd04cf28314 ***

Thread 0 "FoundationPrevi" crashed:

0              0x00007fd04cf28314 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 308 in libswiftCore.so
1 [ra]         0x00007fd04cf280c2 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 257 in libswiftCore.so
2 [ra]         0x00007fd04cf27f7d closure #1 in _assertionFailure(_:_:file:line:flags:) + 380 in libswiftCore.so
3 [ra]         0x00007fd04d0a4576 _assertionFailure(_:_:file:line:flags:) + 229 in libswiftCore.so
4 [ra]         0x00005603dcd72531 JSONEncoderTests._run_failTest<A>(name:type:) + 448 in FoundationPreviewPackageTests.xctest at /build/swift-foundation/Tests/FoundationEssentialsTests/JSONEncoderTests.swift:2402:101
5 [ra]         0x00005603dcd72910 JSONEncoderTests.test_JSONFailTests() + 95 in FoundationPreviewPackageTests.xctest at /build/swift-foundation/Tests/FoundationEssentialsTests/JSONEncoderTests.swift:2415:9
6 [ra]         0x00005603dd3644eb implicit closure #152 in implicit closure #151 in variable initialization expression of staerror: Exited with unexpected signal code 4
tic JSONEncoderTests.__allTests__JSONEncoderTests + 26 in FoundationPreviewPackageTests.xctest at /build/swift-foundation/.build/x86_64-unknown-linux-gnu/debug/FoundationPreviewPackageDiscoveredTests.derived/FoundationEssentialsTests.swift:507:32
7 [ra] [thunk] 0x00005603dd34daef thunk for @escaping @callee_guaranteed () -> (@error @owned Error) + 14 in FoundationPreviewPackageTests.xctest at //<compiler-generated>
8 [ra] [thunk] 0x00005603dd37ad64 thunk for @escaping @callee_guaranteed () -> (@error @owned Error)partial apply + 19 in FoundationPreviewPackageTests.xctest at //<compiler-generated>
```

**Comment by kateinoigakukun** [comment]
Hmm, at least we haven't touched JSONEncoder stuff in WASI support changes.

**Comment by jmschonfeld** [comment]
That failure was a regression caused by a change in SwiftPM, which was fixed on `main` by @xedin with https://github.com/apple/swift-foundation/pull/855 but AFAICT that change was not cherry-picked back to `release/6.0`. @xedin - was the SwiftPM change cherry-picked to `release/6.0`? If so we'll need to cherry pick your test fix as well to unblock swift-foundation testing

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by xedin** [comment]
@jmschonfeld No, the changes I made to SwiftPM are main branch only, there weren't cherry-picked to release/6.0

**Comment by bnbarham** [comment]
> @jmschonfeld No, the changes I made to SwiftPM are main branch only, there weren't cherry-picked to release/6.0

Worth noting though that it is currently using the incorrect path anyway, it's quite possible that the build plan changed here *somehow*. We should definitely cherry-pick the test fix, it's very safe.

**Comment by xedin** [comment]
@swhitty please test Linux platform

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Review by itingliu — APPROVED** [review]
We don't have extra commits here that need to be merged back into `main`, right?

**Comment by MaxDesiatov** [comment]
No, https://github.com/apple/swift-foundation/pull/825/commits/07a59d58224eeefea706d57cea16aedc6f519382 is already on `main`.

**Pull request merged**
