### PR TITLE
Enable reading attributes of directory on Windows (#770)

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
This is a cherry-pick of the change by @jmschonfeld to release/6.0.

**Comment by jmschonfeld** [comment]
Let's wait for @parkera on this before merging - he was in the process of merging `main` to `release/6.0` so that we don't need to cherry-pick every commit individually yet

**Comment by parkera** [comment]
Yah, I'll pick this up shortly. The plan is to merge one more time from main to release/6.0 then cherry-pick after that.

**Comment by compnerd** [comment]
Oh, awesome, then I don't need to fill out the silly form!

**Comment by parkera** [comment]
#772

**Pull request closed without merging**
