### PR TITLE
Implement unlocalized range(of:) for AttributedString

### PR DESCRIPTION
**Pull request by itingliu**
`String` has a natively-implemented `_range(of:options:)`. This PR implements `AttributedString`'s `range(of:options:)` with that when localization support is not needed.

Ideally we should implement this on `BigString` to avoid iterating through `Characters`, which is tracked as a future TODO.
    
This function takes a `Locale` argument, which isn't available in FoundationEssentials. We could move this to FoundationInternalization where `Locale` is defined, but some clients use it with `locale: nil` and do not need localized results. To make the best of this let's add a non-localized version for FoundationEssentials.

### CODE REVIEW

**Comment by itingliu** [comment]
@swift-ci please test

**Review by jmschonfeld — APPROVED** [review]
This LGTM, but I'd love to hear @lorentey's thoughts too in case I'm missing anything

**Comment by itingliu** [comment]
@swift-ci please test

**Comment by itingliu** [comment]
@swift-ci please test

**Comment by itingliu** [comment]
Rebased on main and resolved @parkera's previous comment  -- Now that we have `Locale` in Essentials we can enable this API in Essentials where localized result isn't needed 🎉

**Review by parkera — APPROVED** [review]

**Review by iCharlesHu — APPROVED** [review]
🥳

**Pull request merged**
